# welcome.conf
---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
requirements:
    requiredRam:        2.0
    requiredDiskSpace:  10.0
    internetCheckUrl:   http://example.com
    requiredPower:      false
    requiredInternet:   false
    swap:               false
    displayLicensing:   false
