# settings.conf for Omybuntu Calamares Installer
---
modules-search: [ local ]

instances:
  - id:       language-fallback
    module:   shellprocess
    config:   shellprocess-language.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - grubcfg
    - bootloader
    - shellprocess@language-fallback
    - umount
  - show:
    - finished

branding: omybuntu
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
